defaultPortal: igomoon-coding-task
portals:
  - name: igomoon-coding-task
    portalId: 24949029
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CJip6Ki0LxIJAA0AAAAA4A0DGKXi8gsg_oqrDCju6QwyFA68-t9LcRry84Zo3wXV45U21u48OigAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgQhQyJMrnVcvtFg0M6E9aJqYGG4Uz_koDZXUx
        expiresAt: '2021-08-14T14:39:02.301Z'
    personalAccessKey: >-
      CiRldTEtMzVkNS0zYWVhLTQwZjAtYjIwZS05N2E0OThmNTE0N2QQpeLyCxj-iqsMKhkABeaRgiIu3cr2MYlDl6zRVesNI6JKfylWSgNldTE
