defaultPortal: igomoon-coding-task
portals:
  - name: igomoon-coding-task
    portalId: 24949029
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CLjNg920LxIJAA0AAAAA4A0DGKXi8gsg_oqrDCju6QwyFG3i5_VzZI-P_Z2ClIGjEq9t6VAUOigAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgQhSzR57l8sWpb-buv0U5fRYm3h7FhkoDZXUx
        expiresAt: '2021-08-15T21:04:01.214Z'
    personalAccessKey: >-
      CiRldTEtMzVkNS0zYWVhLTQwZjAtYjIwZS05N2E0OThmNTE0N2QQpeLyCxj-iqsMKhkABeaRgiIu3cr2MYlDl6zRVesNI6JKfylWSgNldTE
