defaultPortal: igomoon-coding-task
portals:
  - name: igomoon-coding-task
    portalId: 24949029
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CNif4p65LxIJAA0AAAAA4A0DGKXi8gsg_oqrDCju6QwyFPMPEt2i5eo9xzG0WanCj665a8OmOigAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgQhT_tkyFKC9PuMzWVQS2UHcJPExbs0oDZXUxUgBaAA
        expiresAt: '2021-08-29T21:37:28.540Z'
    personalAccessKey: >-
      CiRldTEtMzVkNS0zYWVhLTQwZjAtYjIwZS05N2E0OThmNTE0N2QQpeLyCxj-iqsMKhkABeaRgiIu3cr2MYlDl6zRVesNI6JKfylWSgNldTE
