defaultPortal: igomoon-coding-task
portals:
  - name: igomoon-coding-task
    portalId: 24949029
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CImj8-24LxIJAA0AAAAA4A0DGKXi8gsg_oqrDCju6QwyFN9nxAF22Kn8wYu8_b6YKOpPpWlYOigAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgQhTaUHelA0k3UvUitkDOK6WnHFKSZUoDZXUxUgBaAA
        expiresAt: '2021-08-28T17:09:27.053Z'
    personalAccessKey: >-
      CiRldTEtMzVkNS0zYWVhLTQwZjAtYjIwZS05N2E0OThmNTE0N2QQpeLyCxj-iqsMKhkABeaRgiIu3cr2MYlDl6zRVesNI6JKfylWSgNldTE
